apiVersion: v1
kind: Pod
metadata: 
  name: dov-pod
  labels: 
    name: dov-pod
    dept: engg
spec:
  containers:
    - name: dov-container
      image: stackupiss/dov-bear:v2
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
        
