apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: bgg-ing
  labels:
    name: bgg-ing
spec: 
  ingressClassName: nginx
  rules:
    - host: bgg-104.248.97.96.nip.io
      http:
        paths:
          - path: /v1
            pathType: Prefix
            backend: 
              service: 
                name: v1-bggapp-svc
                port:
                  number: 8080
          - path: /v2
            pathType: Prefix
            backend: 
              service: 
                name: v2-bggapp-svc
                port:
                  number: 8080