apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bgg-pvc
  labels:
    name: bgg-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests: 
      storage: 1Gi
  storageClassName: do-block-storage