volumes:
  my-data:
networks:
  my-network:

services:
  nwdb:
    image: stackupiss/northwind-db:v1
    volumes:
      - my-data: /var/lib/mysql
    networks:
      - my-network

  nwapp:
    image: stackupiss/northwind-app:v1
    ports:
      - 8080-8090;3000
    environment:
      - DB_HOST=nwdb
      - DB_USER=root
      - DB_PASSWORD=changeit
    networks:
      - my-network