apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonLabels:
  version: v1

namePrefix: v1-
images:
  - name: bggapp-container
    newTag: v1

patchesStrategicMerge:
- patch.yaml