---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-cm
  labels:
    name: wp-cm
data:
  WORDPRESS_DB_USER: root
  WORDPRESS_DB_HOST: wp-db-cluster-mysql-master.wpns.svc.cluster.local
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_TABLE_PREFIX: wp_

---
apiVersion: v1 
kind: Secret
metadata: 
  name: wp-db-secret
  labels:
    name: wp-db-secret
type: Opaque
data:
  WORDPRESS_DB_PASSWORD: cm9vdHJvb3Q=
