apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonLabels:
  version: v2

namePrefix: v2-

images:
  - name: bggapp-container
    newTag: v2

patchesStrategicMerge:
- patch.yaml